#
#																						  ______          __                                                _          
#																						 |  ____|        / _|                                              | |     _   
#																						 | |__    _ __  | |_  ___   _ __  ___  ___  _ __ ___    ___  _ __  | |_  _| |_ 
#																						 |  __|  | '_ \ |  _|/ _ \ | '__|/ __|/ _ \| '_ ` _ \  / _ \| '_ \ | __||_   _|
#																						 | |____ | | | || | | (_) || |  | (__|  __/| | | | | ||  __/| | | || |_   |_|  
#																						 |______||_| |_||_|  \___/ |_|   \___|\___||_| |_| |_| \___||_| |_| \__|       
#																																									   
#																										        	  Enforcement at your fingertips.																																									   
#


config:
 prefix: '&b&lEnforcement&f&l+ &8|'
 version: '1.0.0'
